travis:
  secure:
    BINSTAR_TOKEN: HBgr545Z+eaxUuBJ9VPMpj0oX8c94djSRRbgflHiw3hIlSieBxnhSLF9W9ufxyFr64eh5bSVOqiThI5z8gecz0KX9JKAJ86dQhjw5GTvAHwyl0lEM+bUQnHiLZQxLyW8GxArSynqiGTmPaZjJ+aXzQWg8BMOUtnvwvGhdkROC/AwcdcsJEVQS8/qinmra69QRgxhVcSz1280Xo0gKX7OkHMuJSPlo+8NO0qMYMmr/f9zJ3UE8Lo0vb6egjWbc+FUIy3o9tCkMutlFtoXaMxsHyw0kEmdW1d14K6/aMl/PPkXGyFoms6aMWCnVKP5qPP72s4niBShE+cc7SB5wg9BvAADxpdSeQImLosL78m5IgivFapvjtzPPEexmQfFg8Rr7e1BqmzgKvDIrHVTyqLqOQOvjGO6w1zX40juCjKyxadXX5WmYhWt95phOW+mnUhqY3V/Fu4pkYH3RYepTap7C+NoFr70YhuY4pEVQlpPsRZ7phBI5GXLO3xRG5OvfYNZvEpbwaL+9Iaf3GaBPLzR26CoIZ0HKYLVHg8VtyouyXPML0c5xE+GHWziccOwueJ2gwT/P2Rg3HswAxEjMhdyXzVw96MWf8mdOD/37ysMpaRcwVIyglKq0ZKzVuIYld8RD5tvuH02mBgA8jLfy2tRgXZ26tfqHuZ5zSHRI8ZQj8o=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
