travis:
  secure:
    BINSTAR_TOKEN: EraxEOZzbpUWOqUCc3df89RL2zK4tIwp3+qTB+cFPSHezhf6QAxmfBbK2a7pTttpST3gnS2pT80iJSv9VYS/On2KaA7QbW3xquGlS0JMwpqH68UM9b9hF0ot58AUm8uI9qgDK4zpCqWUDng9U7aSuXhVeBcv6qp93mgvICuhhhLf20wRrg1zWtHuDz7o1jfJLf2SctAGvv8tFxA4FXc51Q1riCLB/0gohaXVRM+MdWwVS1NOETxZ7z2Vd9stvASsGoKqsYJLEU6doZQ71I8NnLAWNRmX0eCoR230thPThX73ORovMHSCLQnPBlVOSt2lvDOnimZbLKjiaCH8VqzyeKXnZ4LYvkMPO+csMK2Gl7+8TIOHB0v6o1TrqimA9xWueTgPKi6m3039XpaEcfCkbUW8lvG9lW1o9mtAhwdOmYkuW/STbeJP4Sis7awqqkXcDDOChWbQpymikKFCDKGyDB+50N7tfnTn8mHpbMhFT9RAKLh7cBsY6q5pb35SY5t5X1llxqD8gmxMpBOp0Ka+KKGybFrQX/+FyUAQ2KVjdQFRGbmCejXinPqmQKWxzO8gWUTPKCXnwSFAebbeki4xbab78YvqVCBR+CkZrfHCFYoOl5SHT03SPNkus6HoQM/QG307JP0dWbpCdwYNsjLWFN1wvRa8GQpOj4anUOurDPY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
