travis:
  secure:
    BINSTAR_TOKEN: Tr/MDVKFPyFDrtxsWIUVheYlLuaRF3CzOxmE29mcBHCehD14KA83mb46ypE4rCqAqMse61y5OVo7ByXF7CFd8wDIniOanCgfhPzXqzrBIAmkl4MFr7w7p2YhVhNrHEhXUgcsFtGtUO8dqeRW72oZVYMqVmg8ABiQoOjfkiTJWEuze/y8aQeBRzQFiEZvOFDrh//JkPA36CBvkWQaeDMBZ4K7cSzfZcGdY7bYfHZS/AB/XNHtDhaFkPQYj71ErqzqZEJfWDEQ/JxBVh68T0g27dpjz8hOMP7yEjfmyV6F6AJzHzVeSqpte+yoSIp6kg5S5BfC8RnQwMtxXB0TDOw0b1GJHDUUTQbrBfDhKdTywKpcZcx88eDcBmGt/SsIQksyOQePhphFok2j5BlmE+uqzN4ypN39oJBGSM7pYJSjv/C7O59sQ/Yfz734XpFIpho14E2NNHuKqBtUSFjPvjzW0xHZg0qJtBFxgQahsYcVX+W68dEzHS4mDs2SjuOTlxzKMKGQTAgfxhBaokitg+sMQxYEZ7FtSXug5IJRMt3q03AOKXiOD0oOZs3vPZ3MnhfSUvKX7mW5/dwcdoSRyyiN218k+LuS2Kr1NKWgwEWFv3GipcaIB8kTWN76ybSPfGfH9ROe/RWdrD1OLA6rWOjokpPrIlEJoN9KGWiwgm9DfS0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
